var res = {
	
	//commonAlert
	loading_dengdai : "res/CommonAlert/loading_dengdai.png",
	
    //commonGame
	game_star_small_01 : "res/commonGame/game_star_small_01.png",
	game_star_small_02 : "res/commonGame/game_star_small_02.png",
	comLearn_go_back : "res/commonLearn/comLearn_go_back.png",

	//gameHelper
	Helper_arrow_Left : "res/gameHelper/Helper_arrow_Left.png",
	Helper_arrow_rotate : "res/gameHelper/Helper_arrow_rotate.png",
	Helper_arrow_up : "res/gameHelper/Helper_arrow_up.png",
	game_expression_01 : "res/gameHelper/game_expression_01.png",
	game_expression_02 : "res/gameHelper/game_expression_02.png",
	Helper_hand : "res/gameHelper/Helper_hand.png",	

	//gamePublic
	game_nav_pg : "res/commonGame/game_nav_pg.png",
	game_btn_back : "res/commonGame/game_btn_back.png",
	game_bg_select_titlebar : "res/commonGame/game_bg_select_titlebar.png",
	game_btn_suspend_n : "res/commonGame/game_btn_suspend_n.png",
	game_btn_suspend_s : "res/commonGame/game_btn_suspend_s.png",
	game_nav_current : "res/commonGame/game_nav_current.png",
	game_nav_normal : "res/commonGame/game_nav_normal.png",
	game_nav_pass : "res/commonGame/game_nav_pass.png",
	game_nav_wrong : "res/commonGame/game_nav_wrong.png",

	//startView
	game_panel_start : "res/commonGame/game_panel_start.png",
	game_start_cup : "res/commonGame/game_start_cup.png",
	game_btn_long_n : "res/commonGame/game_btn_long_n.png",
	game_btn_long_s : "res/commonGame/game_btn_long_s.png",

	//pauseView
	game_btn_continue_n : "res/commonGame/game_btn_continue_n.png",
	game_btn_continue_s : "res/commonGame/game_btn_continue_s.png",
	game_btn_help_n : "res/commonGame/game_btn_help_n.png",
	game_btn_help_s : "res/commonGame/game_btn_help_s.png",
	game_btn_restart_n : "res/commonGame/game_btn_restart_n.png",
	game_btn_restart_s : "res/commonGame/game_btn_restart_s.png",
	game_btn_musicOff_n : "res/commonGame/game_btn_musicOff_n.png",
	game_btn_musicOff_s : "res/commonGame/game_btn_musicOff_s.png",
	game_btn_musicOn_n : "res/commonGame/game_btn_musicOn_n.png",
	game_btn_musicOn_s : "res/commonGame/game_btn_musicOn_s.png",
	game_btn_closeSound_n : "res/commonGame/game_btn_closeSound_n.png",
	game_btn_closeSound_s : "res/commonGame/game_btn_closeSound_s.png",
	game_btn_openSound_n : "res/commonGame/game_btn_openSound_n.png",
	game_btn_openSound_s : "res/commonGame/game_btn_openSound_s.png",
	game_btn_menuBack_n : "res/commonGame/game_btn_menuBack_n.png",
	game_btn_menuBack_s : "res/commonGame/game_btn_menuBack_s.png",

	//settleView
	game_panel_settleaccounts : "res/commonGame/game_panel_settleaccounts.png",
	game_star_big_01 : "res/commonGame/game_star_big_01.png",
	game_star_big_02 : "res/commonGame/game_star_big_02.png",
	game_btn_left_n : "res/commonGame/game_btn_left_n.png",
	game_btn_left_s : "res/commonGame/game_btn_left_s.png",
	game_btn_right_n : "res/commonGame/game_btn_right_n.png",
	game_btn_right_s : "res/commonGame/game_btn_right_s.png",
	game_icon_seal : "res/commonGame/game_icon_seal.png",

	//common学能--作业和测试
	comLearn_btn_n : "res/commonLearn/comLearn_btn_n.png",
	comLearn_btn_s : "res/commonLearn/comLearn_btn_s.png",
	comLearn_panel_bg : "res/commonLearn/comLearn_panel_bg.png",
	panel_LC_smalltips : "res/learnTest/panel_LC_smalltips.png",
	panel_small : "res/learnTest/panel_small.png",

	game_x_frame : "res/commonGame/game_x_frame.png",
	game_x_frame_02 : "res/commonGame/game_x_frame_02.png",
	game_x_head : "res/commonGame/game_x_head.png",
	game_x_line : "res/commonGame/game_x_line.png",
	game_x_lock_01 : "res/commonGame/game_x_lock_01.png",
	game_x_lock_02 : "res/commonGame/game_x_lock_02.png",
	game_x_ranking_01 : "res/commonGame/game_x_ranking_01.png",
	game_x_ranking_02 : "res/commonGame/game_x_ranking_02.png",
	game_x_ranking_03 : "res/commonGame/game_x_ranking_03.png",
	game_x_ranking_04 : "res/commonGame/game_x_ranking_04.png",
	game_x_ranking_05 : "res/commonGame/game_x_ranking_05.png",
	game_x_star_least : "res/commonGame/game_x_star_least.png",
	game_btn_lock_n : "res/commonGame/game_btn_lock_n.png",
	game_btn_lock_s : "res/commonGame/game_btn_lock_s.png",
	game_panel_lock : "res/commonGame/game_panel_lock.png",

	//game
	game : {
		//gameLobby
		game_icon_colorMachine : "res/gameCell/game_icon_colorMachine.png",
		game_icon_numberCrash : "res/gameCell/game_icon_numberCrash.png",
		game_icon_positionmemory : "res/gameCell/game_icon_positionmemory.png",
		game_icon_schultegrid : "res/gameCell/game_icon_schultegrid.png",
		game_icon_seabed : "res/gameCell/game_icon_seabed.png",
		game_icon_newWorlds : "res/gameCell/game_icon_newWorlds.png",
		game_icon_tangram : "res/gameCell/game_icon_tangram.png",
		game_icon_pleaselook : "res/gameCell/game_icon_pleaselook.png",
		game_icon_painting : "res/gameCell/game_icon_painting.png",
		game_icon_stack : "res/gameCell/game_icon_stack.png",
		game_icon_fish : "res/gameCell/game_icon_fish.png",
		//chooseLevel
		game_pagebreak_01 : "res/commonGame/game_pagebreak_01.png",
		game_pagebreak_02 : "res/commonGame/game_pagebreak_02.png",
		game_gameLevel_01 : "res/commonGame/game_gameLevel_01.png",
		game_gameLevel_02 : "res/commonGame/game_gameLevel_02.png",
	},

	//learnTest
	learnTest : {
		bnt_lc_starttest_n : "res/learnTest/bnt_lc_starttest_n.png",
		bnt_lc_starttest_s : "res/learnTest/bnt_lc_starttest_s.png",
		LearnWork_bg_lower : "res/learnTask/LearnWork_bg_lower.png",
		lc_pic : "res/learnTest/lc_pic.png",
		lc_nav_current : "res/learnTest/lc_nav_current.png",
		lc_nav_normal : "res/learnTest/lc_nav_normal.png",
		lc_nav_pass : "res/learnTest/lc_nav_pass.png",
		lc_nav_wrong : "res/learnTest/lc_nav_wrong.png",
		bnt_lc_btc_n : "res/learnTest/bnt_lc_btc_n.png",
		bnt_lc_btc_s : "res/learnTest/bnt_lc_btc_s.png",
		lc_dashboard_01 : "res/learnTest/lc_dashboard_01.png",
		lc_dashboard_02 : "res/learnTest/lc_dashboard_02.png",
		lc_dashboard_03 : "res/learnTest/lc_dashboard_03.png",
		lc_explain : "res/learnTest/lc_explain.png",
		LC_titlebar : "res/learnTest/LC_titlebar.png",
		LC_titlebar_bg : "res/learnTest/LC_titlebar_bg.png",
		LC_Level_01: "res/learnTest/LC_Level_01.png",
	},

	//learnTask
	learnTask : {
		colorMachine_icon_small : "res/learnTask/colorMachine_icon_small.png",
		LearnWork_newWorlds_small : "res/learnTask/LearnWork_newWorlds_small.png",
		LearnWork_numberCrash_small : "res/learnTask/LearnWork_numberCrash_small.png",
		LearnWork_positionmemory_small : "res/learnTask/LearnWork_positionmemory_small.png",
		LearnWork_schultegrid_small : "res/learnTask/LearnWork_schultegrid_small.png",
		LearnWork_seabed_small : "res/learnTask/LearnWork_seabed_small.png",
		LearnWork_tangram_small : "res/learnTask/LearnWork_tangram_small.png",
		LearnWork_Thedottedline : "res/learnTask/LearnWork_Thedottedline.png",
		LearnWork_Thedottedline02 : "res/learnTask/LearnWork_Thedottedline02.png",
		LearnWork_fish_small : "res/learnTask/LearnWork_fish_small.png",
		LearnWork_stack_small : "res/learnTask/LearnWork_stack_small.png",
		LearnWork_painting_small : "res/learnTask/LearnWork_painting_small.png",
		LC_smallarrow_d : "res/learnTest/LC_smallarrow_d.png",
		LC_smallarrow_n : "res/learnTest/LC_smallarrow_n.png",
		LearnWork_triangle_n :"res/learnTask/LearnWork_triangle_n.png",
		LearnWork_triangle_s :"res/learnTask/LearnWork_triangle_s.png",
		lc_menubar_n : "res/learnTest/lc_menubar_n.png",
		LearnWork_nav_normal : "res/learnTask/LearnWork_nav_normal.png",
		LearnWork_nav_pass : "res/learnTask/LearnWork_nav_pass.png",
		bnt_LearnWork_StartJobs_n : "res/learnTask/bnt_LearnWork_StartJobs_n.png",
		bnt_LearnWork_StartJobs_s : "res/learnTask/bnt_LearnWork_StartJobs_s.png",
		LearnWork_nav_current : "res/learnTask/LearnWork_nav_current.png",
		LearnWork_nav_wrong : "res/learnTask/LearnWork_nav_wrong.png",
	},

    //numberCrash
    numberCrash : {
		nc_label_small : "res/numberCrash/nc_label_small.png",
		nc_nva_progressBar : "res/numberCrash/nc_nva_progressBar.png",
		nc_nva_progressBar_bg : "res/numberCrash/nc_nva_progressBar_bg.png",
		nc_square_01 : "res/numberCrash/nc_square_01.png",
		nc_square_02 : "res/numberCrash/nc_square_02.png",
		nc_square_03 : "res/numberCrash/nc_square_03.png",
		nc_square_04 : "res/numberCrash/nc_square_04.png",
		nc_square_05 : "res/numberCrash/nc_square_05.png",
    },

    //colorMachine
    colorMachine : {
		cm_colourDisk_black : "res/colorMachine/cm_colourDisk_black.png",
		cm_colourDisk_black02 : "res/colorMachine/cm_colourDisk_black02.png",
		cm_colourDisk_blue : "res/colorMachine/cm_colourDisk_blue.png",
		cm_colourDisk_blue02 : "res/colorMachine/cm_colourDisk_blue02.png",
		cm_colourDisk_brown : "res/colorMachine/cm_colourDisk_brown.png",
		cm_colourDisk_brown02 : "res/colorMachine/cm_colourDisk_brown02.png",
		cm_colourDisk_green : "res/colorMachine/cm_colourDisk_green.png",
		cm_colourDisk_green02 : "res/colorMachine/cm_colourDisk_green02.png",
		cm_colourDisk_purple : "res/colorMachine/cm_colourDisk_purple.png",
		cm_colourDisk_purple02 : "res/colorMachine/cm_colourDisk_purple02.png",
		cm_colourDisk_red : "res/colorMachine/cm_colourDisk_red.png",
		cm_colourDisk_red02 : "res/colorMachine/cm_colourDisk_red02.png",
		cm_colourDisk_whit02 : "res/colorMachine/cm_colourDisk_whit02.png",
		cm_colourDisk_white : "res/colorMachine/cm_colourDisk_white.png",
		cm_colourDisk_yellow : "res/colorMachine/cm_colourDisk_yellow.png",
		cm_colourDisk_yellow02 : "res/colorMachine/cm_colourDisk_yellow02.png",
		cm_icon_exactness : "res/colorMachine/cm_icon_exactness.png",
		cm_icon_wrong : "res/colorMachine/cm_icon_wrong.png",
		cm_icon_wrong_circular : "res/colorMachine/cm_icon_wrong_circular.png",
		cm_nav_progressBar_ : "res/colorMachine/cm_nav_progressBar_.png",
		cm_nva_progressBar : "res/colorMachine/cm_nva_progressBar.png",
		cm_nva_progressBar_bg : "res/colorMachine/cm_nva_progressBar_bg.png",
		game_btn_select_titlebar_n : "res/commonGame/game_btn_select_titlebar_n.png",
		game_btn_select_titlebar_s : "res/commonGame/game_btn_select_titlebar_s.png",
    },
    
    //positionMemory
    posMem : {
	    pm_pattern_01 : "res/positionMemory/pm_pattern_01.png",
	    pm_pattern_02 : "res/positionMemory/pm_pattern_02.png",
	    pm_pattern_03 : "res/positionMemory/pm_pattern_03.png",
	    pm_pattern_cuo : "res/positionMemory/pm_pattern_cuo.png",
	    pm_pattern_pg : "res/positionMemory/pm_pattern_pg.png",
	},

    //schulteGrid
    schulte : {
	    sg_square_01:"res/schulteGrid/sg_square_01.png",
	    sg_square_02:"res/schulteGrid/sg_square_02.png",
	    sg_square_03:"res/schulteGrid/sg_square_03.png",
	    sg_square_04:"res/schulteGrid/sg_square_04.png",
	    sg_nav_progressbar:"res/schulteGrid/sg_nav_progressbar.png",
    },

    //seabedMobilze
    seabed : {
    	seabed_bg_03 : "res/seabedMobilze/seabed_bg_03.png",
		seabed_bg_seabed : "res/seabedMobilze/seabed_bg_seabed.png",
		seabed_bg_settlement01 : "res/seabedMobilze/seabed_bg_settlement01.png",
		seabed_bg_settlement02 : "res/seabedMobilze/seabed_bg_settlement02.png",
		seabed_bubble : "res/seabedMobilze/seabed_bubble.png",
		seabed_fish_blue01a : "res/seabedMobilze/seabed_fish_blue01a.png",
		seabed_fish_blue01b : "res/seabedMobilze/seabed_fish_blue01b.png",
		seabed_fish_blue02a : "res/seabedMobilze/seabed_fish_blue02a.png",
		seabed_fish_blue02b : "res/seabedMobilze/seabed_fish_blue02b.png",
		seabed_fish_blue03a : "res/seabedMobilze/seabed_fish_blue03a.png",
		seabed_fish_blue03b : "res/seabedMobilze/seabed_fish_blue03b.png",
		seabed_fish_blue04a : "res/seabedMobilze/seabed_fish_blue04a.png",
		seabed_fish_blue04b : "res/seabedMobilze/seabed_fish_blue04b.png",
		seabed_fish_blue05a : "res/seabedMobilze/seabed_fish_blue05a.png",
		seabed_fish_blue05b : "res/seabedMobilze/seabed_fish_blue05b.png",
		seabed_fish_green01a : "res/seabedMobilze/seabed_fish_green01a.png",
		seabed_fish_green01b : "res/seabedMobilze/seabed_fish_green01b.png",
		seabed_fish_green02a : "res/seabedMobilze/seabed_fish_green02a.png",
		seabed_fish_green02b : "res/seabedMobilze/seabed_fish_green02b.png",
		seabed_fish_green03a : "res/seabedMobilze/seabed_fish_green03a.png",
		seabed_fish_green03b : "res/seabedMobilze/seabed_fish_green03b.png",
		seabed_fish_green04a : "res/seabedMobilze/seabed_fish_green04a.png",
		seabed_fish_green04b : "res/seabedMobilze/seabed_fish_green04b.png",
		seabed_fish_green05a : "res/seabedMobilze/seabed_fish_green05a.png",
		seabed_fish_green05b : "res/seabedMobilze/seabed_fish_green05b.png",
		seabed_fish_pink01a : "res/seabedMobilze/seabed_fish_pink01a.png",
		seabed_fish_pink01b : "res/seabedMobilze/seabed_fish_pink01b.png",
		seabed_fish_pink02a : "res/seabedMobilze/seabed_fish_pink02a.png",
		seabed_fish_pink02b : "res/seabedMobilze/seabed_fish_pink02b.png",
		seabed_fish_pink03a : "res/seabedMobilze/seabed_fish_pink03a.png",
		seabed_fish_pink03b : "res/seabedMobilze/seabed_fish_pink03b.png",
		seabed_fish_pink04a : "res/seabedMobilze/seabed_fish_pink04a.png",
		seabed_fish_pink04b : "res/seabedMobilze/seabed_fish_pink04b.png",
		seabed_fish_pink05a : "res/seabedMobilze/seabed_fish_pink05a.png",
		seabed_fish_pink05b : "res/seabedMobilze/seabed_fish_pink05b.png",
		seabed_fish_purple01a : "res/seabedMobilze/seabed_fish_purple01a.png",
		seabed_fish_purple01b : "res/seabedMobilze/seabed_fish_purple01b.png",
		seabed_fish_purple02a : "res/seabedMobilze/seabed_fish_purple02a.png",
		seabed_fish_purple02b : "res/seabedMobilze/seabed_fish_purple02b.png",
		seabed_fish_purple03a : "res/seabedMobilze/seabed_fish_purple03a.png",
		seabed_fish_purple03b : "res/seabedMobilze/seabed_fish_purple03b.png",
		seabed_fish_purple04a : "res/seabedMobilze/seabed_fish_purple04a.png",
		seabed_fish_purple04b : "res/seabedMobilze/seabed_fish_purple04b.png",
		seabed_fish_purple05a : "res/seabedMobilze/seabed_fish_purple05a.png",
		seabed_fish_purple05b : "res/seabedMobilze/seabed_fish_purple05b.png",
		seabed_fish_yelloe01a : "res/seabedMobilze/seabed_fish_yelloe01a.png",
		seabed_fish_yelloe01b : "res/seabedMobilze/seabed_fish_yelloe01b.png",
		seabed_fish_yelloe02a : "res/seabedMobilze/seabed_fish_yelloe02a.png",
		seabed_fish_yelloe02b : "res/seabedMobilze/seabed_fish_yelloe02b.png",
		seabed_fish_yelloe03a : "res/seabedMobilze/seabed_fish_yelloe03a.png",
		seabed_fish_yelloe03b : "res/seabedMobilze/seabed_fish_yelloe03b.png",
		seabed_fish_yelloe04a : "res/seabedMobilze/seabed_fish_yelloe04a.png",
		seabed_fish_yelloe04b : "res/seabedMobilze/seabed_fish_yelloe04b.png",
		seabed_fish_yelloe05a : "res/seabedMobilze/seabed_fish_yelloe05a.png",
		seabed_fish_yelloe05b : "res/seabedMobilze/seabed_fish_yelloe05b.png",
		seabed_fishbowl : "res/seabedMobilze/seabed_fishbowl.png",
		seabed_obstacle : "res/seabedMobilze/seabed_obstacle.png",
    },

	//sevenPuzzle
	tangram : {
		cm_nav_progressBar_ : "res/colorMachine/cm_nav_progressBar_.png",
		tangram_bnt_rotate : "res/sevenPuzzle/tangram_bnt_rotate.png",
		tangram_bg_a : "res/sevenPuzzle/tangram_bg_a.png",
		tangram_icon_01a : "res/sevenPuzzle/tangram_icon_01a.png",
		tangram_icon_01b : "res/sevenPuzzle/tangram_icon_01b.png",
		tangram_icon_01c : "res/sevenPuzzle/tangram_icon_01c.png",
		tangram_icon_01d : "res/sevenPuzzle/tangram_icon_01d.png",
		tangram_icon_02a : "res/sevenPuzzle/tangram_icon_02a.png",
		tangram_icon_02b : "res/sevenPuzzle/tangram_icon_02b.png",
		tangram_icon_02c : "res/sevenPuzzle/tangram_icon_02c.png",
		tangram_icon_02d : "res/sevenPuzzle/tangram_icon_02d.png",
		tangram_icon_03a : "res/sevenPuzzle/tangram_icon_03a.png",
		tangram_icon_03b : "res/sevenPuzzle/tangram_icon_03b.png",
		tangram_icon_03c : "res/sevenPuzzle/tangram_icon_03c.png",
		tangram_icon_03d : "res/sevenPuzzle/tangram_icon_03d.png",
		tangram_icon_04a : "res/sevenPuzzle/tangram_icon_04a.png",
		tangram_icon_04b : "res/sevenPuzzle/tangram_icon_04b.png",
		tangram_icon_04c : "res/sevenPuzzle/tangram_icon_04c.png",
		tangram_icon_04d : "res/sevenPuzzle/tangram_icon_04d.png",
		tangram_icon_05a : "res/sevenPuzzle/tangram_icon_05a.png",
		tangram_icon_05b : "res/sevenPuzzle/tangram_icon_05b.png",
		tangram_icon_05c : "res/sevenPuzzle/tangram_icon_05c.png",
		tangram_icon_05d : "res/sevenPuzzle/tangram_icon_05d.png",
		tangram_icon_06a : "res/sevenPuzzle/tangram_icon_06a.png",
		tangram_icon_06b : "res/sevenPuzzle/tangram_icon_06b.png",
		tangram_icon_06c : "res/sevenPuzzle/tangram_icon_06c.png",
		tangram_icon_06d : "res/sevenPuzzle/tangram_icon_06d.png",
		tangram_icon_07a : "res/sevenPuzzle/tangram_icon_07a.png",
		tangram_icon_07b : "res/sevenPuzzle/tangram_icon_07b.png",
		tangram_icon_07c : "res/sevenPuzzle/tangram_icon_07c.png",
		tangram_icon_07d : "res/sevenPuzzle/tangram_icon_07d.png",
	},

	//tangramLevel
	tangramLevel : {
		1 : {
				tangram_bgA_09 : "res/sevenPuzzle/tangram_bgA_09.png",
				tangram_bgA_14 : "res/sevenPuzzle/tangram_bgA_14.png",
				tangram_bgA_15 : "res/sevenPuzzle/tangram_bgA_15.png",
		},
		2 : {
				tangram_bgA_10 : "res/sevenPuzzle/tangram_bgA_10.png",
				tangram_bgA_11 : "res/sevenPuzzle/tangram_bgA_11.png",
				tangram_bgA_13 : "res/sevenPuzzle/tangram_bgA_13.png",
		},
		3 : {
				tangram_bgA_03 : "res/sevenPuzzle/tangram_bgA_03.png",
				tangram_bgA_02 : "res/sevenPuzzle/tangram_bgA_02.png",
				tangram_bgA_01 : "res/sevenPuzzle/tangram_bgA_01.png",
		},
		4 : {
				tangram_bgA_04 : "res/sevenPuzzle/tangram_bgA_04.png",
				tangram_bgA_05 : "res/sevenPuzzle/tangram_bgA_05.png",
				tangram_bgA_06 : "res/sevenPuzzle/tangram_bgA_06.png",
		},
		5 : {
				tangram_bgA_07 : "res/sevenPuzzle/tangram_bgA_07.png",
				tangram_bgA_08 : "res/sevenPuzzle/tangram_bgA_08.png",	
				tangram_bgA_12 : "res/sevenPuzzle/tangram_bgA_12.png",
		},
		6 : {
				tangram_bgB_30 : "res/sevenPuzzle/tangram_bgB_30.png",
				tangram_bgB_31 : "res/sevenPuzzle/tangram_bgB_31.png",
				tangram_bgB_32 : "res/sevenPuzzle/tangram_bgB_32.png",
		},
		7 : {
				tangram_bgB_01 : "res/sevenPuzzle/tangram_bgB_01.png",
				tangram_bgB_02 : "res/sevenPuzzle/tangram_bgB_02.png",
				tangram_bgB_75 : "res/sevenPuzzle/tangram_bgB_75.png",
		},
		8 : {
				tangram_bgB_18 : "res/sevenPuzzle/tangram_bgB_18.png",
				tangram_bgB_19 : "res/sevenPuzzle/tangram_bgB_19.png",
				tangram_bgB_20 : "res/sevenPuzzle/tangram_bgB_20.png",
		},
		9 : {
				tangram_bgB_55 : "res/sevenPuzzle/tangram_bgB_55.png",
				tangram_bgB_56 : "res/sevenPuzzle/tangram_bgB_56.png",
				tangram_bgB_61 : "res/sevenPuzzle/tangram_bgB_61.png",
		},
		10 : {
				tangram_bgB_66 : "res/sevenPuzzle/tangram_bgB_66.png",
				tangram_bgB_67 : "res/sevenPuzzle/tangram_bgB_67.png",
				tangram_bgB_68 : "res/sevenPuzzle/tangram_bgB_68.png",
		},
		11 : {
				tangram_bgB_06 : "res/sevenPuzzle/tangram_bgB_06.png",
				tangram_bgB_07 : "res/sevenPuzzle/tangram_bgB_07.png",
				tangram_bgB_08 : "res/sevenPuzzle/tangram_bgB_08.png",
		},
		12 : {
				tangram_bgB_50 : "res/sevenPuzzle/tangram_bgB_50.png",
				tangram_bgB_51 : "res/sevenPuzzle/tangram_bgB_51.png",
				tangram_bgB_52 : "res/sevenPuzzle/tangram_bgB_52.png",
		},
		13 : {
				tangram_bgB_12 : "res/sevenPuzzle/tangram_bgB_12.png",
				tangram_bgB_13 : "res/sevenPuzzle/tangram_bgB_13.png",
				tangram_bgB_14 : "res/sevenPuzzle/tangram_bgB_14.png",
		},
		14 : {
				tangram_bgB_59 : "res/sevenPuzzle/tangram_bgB_59.png",
				tangram_bgB_60 : "res/sevenPuzzle/tangram_bgB_60.png",
				tangram_bgB_63 : "res/sevenPuzzle/tangram_bgB_63.png",
		},
		15 : {
				tangram_bgB_53 : "res/sevenPuzzle/tangram_bgB_53.png",
				tangram_bgB_54 : "res/sevenPuzzle/tangram_bgB_54.png",
				tangram_bgB_57 : "res/sevenPuzzle/tangram_bgB_57.png",
		},
		16 : {
				tangram_bgB_09 : "res/sevenPuzzle/tangram_bgB_09.png",
				tangram_bgB_10 : "res/sevenPuzzle/tangram_bgB_10.png",
				tangram_bgB_11 : "res/sevenPuzzle/tangram_bgB_11.png",
		},
		17 : {
				tangram_bgB_36 : "res/sevenPuzzle/tangram_bgB_36.png",
				tangram_bgB_37 : "res/sevenPuzzle/tangram_bgB_37.png",
				tangram_bgB_38 : "res/sevenPuzzle/tangram_bgB_38.png",
		},
		18 : {
				tangram_bgB_24 : "res/sevenPuzzle/tangram_bgB_24.png",
				tangram_bgB_25 : "res/sevenPuzzle/tangram_bgB_25.png",
				tangram_bgB_26 : "res/sevenPuzzle/tangram_bgB_26.png",
		},
		19 : {
				tangram_bgB_27 : "res/sevenPuzzle/tangram_bgB_27.png",
				tangram_bgB_28 : "res/sevenPuzzle/tangram_bgB_28.png",
				tangram_bgB_29 : "res/sevenPuzzle/tangram_bgB_29.png",
		},
		20 : {
				tangram_bgB_33 : "res/sevenPuzzle/tangram_bgB_33.png",
				tangram_bgB_34 : "res/sevenPuzzle/tangram_bgB_34.png",
				tangram_bgB_35 : "res/sevenPuzzle/tangram_bgB_35.png",
		},
		21 : {
				tangram_bgB_39 : "res/sevenPuzzle/tangram_bgB_39.png",
				tangram_bgB_41 : "res/sevenPuzzle/tangram_bgB_41.png",
				tangram_bgB_42 : "res/sevenPuzzle/tangram_bgB_42.png",
		},
		22 : {
				tangram_bgB_43 : "res/sevenPuzzle/tangram_bgB_43.png",
				tangram_bgB_45 : "res/sevenPuzzle/tangram_bgB_45.png",
				tangram_bgB_46 : "res/sevenPuzzle/tangram_bgB_46.png",
		},
		23 : {
				tangram_bgB_40 : "res/sevenPuzzle/tangram_bgB_40.png",
				tangram_bgB_44 : "res/sevenPuzzle/tangram_bgB_44.png",
				tangram_bgB_62 : "res/sevenPuzzle/tangram_bgB_62.png",
		},
		24 : {
				tangram_bgB_47 : "res/sevenPuzzle/tangram_bgB_47.png",
				tangram_bgB_48 : "res/sevenPuzzle/tangram_bgB_48.png",
				tangram_bgB_49 : "res/sevenPuzzle/tangram_bgB_49.png",
		},
		25 : {
				tangram_bgB_69 : "res/sevenPuzzle/tangram_bgB_69.png",
				tangram_bgB_70 : "res/sevenPuzzle/tangram_bgB_70.png",
				tangram_bgB_71 : "res/sevenPuzzle/tangram_bgB_71.png",
		},
		26 : {
				tangram_bgB_58 : "res/sevenPuzzle/tangram_bgB_58.png",
				tangram_bgB_64 : "res/sevenPuzzle/tangram_bgB_64.png",
				tangram_bgB_65 : "res/sevenPuzzle/tangram_bgB_65.png",
		},
		27 : {
				tangram_bgB_15 : "res/sevenPuzzle/tangram_bgB_15.png",
				tangram_bgB_16 : "res/sevenPuzzle/tangram_bgB_16.png",
				tangram_bgB_17 : "res/sevenPuzzle/tangram_bgB_17.png",
		},
		28 : {
				tangram_bgB_03 : "res/sevenPuzzle/tangram_bgB_03.png",
				tangram_bgB_04 : "res/sevenPuzzle/tangram_bgB_04.png",
				tangram_bgB_05 : "res/sevenPuzzle/tangram_bgB_05.png",
		},
		29 : {
				tangram_bgB_72 : "res/sevenPuzzle/tangram_bgB_72.png",
				tangram_bgB_73 : "res/sevenPuzzle/tangram_bgB_73.png",
				tangram_bgB_74 : "res/sevenPuzzle/tangram_bgB_74.png",
		},
		30 : {
				tangram_bgB_21 : "res/sevenPuzzle/tangram_bgB_21.png",
				tangram_bgB_22 : "res/sevenPuzzle/tangram_bgB_22.png",
				tangram_bgB_23 : "res/sevenPuzzle/tangram_bgB_23.png",
		}
	},

	//newWords
	newWords : {
		youxi_newWorlds_back :"res/newWords/youxi_newWorlds_back.png",
		youxi_newWorlds_backBig :"res/newWords/youxi_newWorlds_backBig.png",
		youxi_newWorlds_Normal :"res/newWords/youxi_newWorlds_Normal.png",
		youxi_newWorlds_normalBig :"res/newWords/youxi_newWorlds_normalBig.png",
		youxi_newWorlds_Selected :"res/newWords/youxi_newWorlds_Selected.png",
		youxi_newWorlds_Wrong :"res/newWords/youxi_newWorlds_Wrong.png",
		newWorlds_nav_progressbar :"res/newWords/newWorlds_nav_progressbar.png",
	},

	//stackChart
	stackChart : {
		stack_nva_progressBar_bg : "res/stackChart/stack_nva_progressBar_bg.png",
		stack_nva_progressBar_bg02 : "res/stackChart/stack_nva_progressBar_bg02.png",
		stack_large_0 : "res/stackChart/stack_large_0.png",
		stack_large_1 : "res/stackChart/stack_large_1.png",
		stack_large_2 : "res/stackChart/stack_large_2.png",
		stack_large_3 : "res/stackChart/stack_large_3.png",
		stack_large_4 : "res/stackChart/stack_large_4.png",
		stack_large_5 : "res/stackChart/stack_large_5.png",
		stack_medium_0 : "res/stackChart/stack_medium_0.png",
		stack_medium_1 : "res/stackChart/stack_medium_1.png",
		stack_medium_2 : "res/stackChart/stack_medium_2.png",
		stack_medium_3 : "res/stackChart/stack_medium_3.png",
		stack_medium_4 : "res/stackChart/stack_medium_4.png",
		stack_medium_5 : "res/stackChart/stack_medium_5.png",
		stack_nva_progressBar : "res/stackChart/stack_nva_progressBar.png",
		stack_side_large_0 : "res/stackChart/stack_side_large_0.png",
		stack_side_large_1 : "res/stackChart/stack_side_large_1.png",
		stack_side_large_2 : "res/stackChart/stack_side_large_2.png",
		stack_side_large_3 : "res/stackChart/stack_side_large_3.png",
		stack_side_large_4 : "res/stackChart/stack_side_large_4.png",
		stack_side_large_5 : "res/stackChart/stack_side_large_5.png",
		stack_side_medium_0 : "res/stackChart/stack_side_medium_0.png",
		stack_side_medium_1 : "res/stackChart/stack_side_medium_1.png",
		stack_side_medium_2 : "res/stackChart/stack_side_medium_2.png",
		stack_side_medium_3 : "res/stackChart/stack_side_medium_3.png",
		stack_side_medium_4 : "res/stackChart/stack_side_medium_4.png",
		stack_side_medium_5 : "res/stackChart/stack_side_medium_5.png",
		stack_side_small_0 : "res/stackChart/stack_side_small_0.png",
		stack_side_small_1 : "res/stackChart/stack_side_small_1.png",
		stack_side_small_2 : "res/stackChart/stack_side_small_2.png",
		stack_side_small_3 : "res/stackChart/stack_side_small_3.png",
		stack_side_small_4 : "res/stackChart/stack_side_small_4.png",
		stack_side_small_5 : "res/stackChart/stack_side_small_5.png",
		stack_small_0 : "res/stackChart/stack_small_0.png",
		stack_small_1 : "res/stackChart/stack_small_1.png",
		stack_small_2 : "res/stackChart/stack_small_2.png",
		stack_small_3 : "res/stackChart/stack_small_3.png",
		stack_small_4 : "res/stackChart/stack_small_4.png",
		stack_small_5 : "res/stackChart/stack_small_5.png",
		stack_sure : "res/stackChart/stack_sure.png",
		stack_wrong : "res/stackChart/stack_wrong.png",
		stack_wrong_bg02 : "res/stackChart/stack_wrong_bg02.png",
		stacks_bkg : "res/stackChart/stacks_bkg.png",
		transparent : "res/stackChart/transparent.png",
	},

	//paintedPath
	paintedPath : {
		Painting_Block_0 : "res/paintedPath/Painting_Block_0.png",
		Painting_Block_01 : "res/paintedPath/Painting_Block_01.png",
		Painting_Block_02 : "res/paintedPath/Painting_Block_02.png",
		Painting_Block_03 : "res/paintedPath/Painting_Block_03.png",
		Painting_Block_04 : "res/paintedPath/Painting_Block_04.png",
		Painting_Block_05 : "res/paintedPath/Painting_Block_05.png",
		Painting_Block_06 : "res/paintedPath/Painting_Block_06.png",
		Painting_Block_07 : "res/paintedPath/Painting_Block_07.png",
		Painting_Block_08 : "res/paintedPath/Painting_Block_08.png",
		Painting_Block_09 : "res/paintedPath/Painting_Block_09.png",
		Painting_Block_10 : "res/paintedPath/Painting_Block_10.png",
		Painting_Block_11 : "res/paintedPath/Painting_Block_11.png",
		Painting_Block_12 : "res/paintedPath/Painting_Block_12.png",
		Painting__nva_progressBar : "res/paintedPath/Painting__nva_progressBar.png",
		Painting_bg_white : "res/paintedPath/Painting_bg_white.png",
		Painting_circular_1 : "res/paintedPath/Painting_circular_1.png",
		Painting_diamond : "res/paintedPath/Painting_diamond.png",
		Painting_fork : "res/paintedPath/Painting_fork.png",
		Painting_leftarrow_big : "res/paintedPath/Painting_leftarrow_big.png",
		Painting_line_01 : "res/paintedPath/Painting_line_01.png",
		Painting_line_02 : "res/paintedPath/Painting_line_02.png",
		Painting_line_03 : "res/paintedPath/Painting_line_03.png",
		Painting_Block_white : "res/paintedPath/Painting_Block_white.png",
		Painting_circular_02 : "res/paintedPath/Painting_circular_02.png",
		Painting_diamond02 : "res/paintedPath/Painting_diamond02.png",
		Painting_diamond03 : "res/paintedPath/Painting_diamond03.png",
	},

	koiGame : {
		background_jpg : "res/koiGame/background.jpg",
		empty : "res/koiGame/empty.png",
		koi : "res/koiGame/koi/koi.png",

		tint : "res/koiGame/pond/tint.png",
		fish_scene01 : "res/koiGame/pond/fish_scene01.png",
		fish_scene02 : "res/koiGame/pond/fish_scene02.png",
		fish_scene03 : "res/koiGame/pond/fish_scene03.png",
		fish_scene04 : "res/koiGame/pond/fish_scene04.png",
		fish_scene05 : "res/koiGame/pond/fish_scene05.png",
		fish_shade   : "res/koiGame/pond/fish_shade.png",

		food : "res/koiGame/PlayingKoi/graphics/food/food.png",
		foodLocked : "res/koiGame/PlayingKoi/graphics/food/foodLocked.png",
		foodUnlocked : "res/koiGame/PlayingKoi/graphics/food/foodUnlocked.png",
		food_centerContainer : "res/koiGame/PlayingKoi/graphics/food/food_centerContainer.png",
		food_pipContainer : "res/koiGame/PlayingKoi/graphics/food/food_pipContainer.png",
		food_pipRemaining : "res/koiGame/PlayingKoi/graphics/food/food_pipRemaining.png",
		food_pipUsed : "res/koiGame/PlayingKoi/graphics/food/food_pipUsed.png",

		feedback_caret : "res/koiGame/PlayingKoi/graphics/feedback/feedback_caret.png",
		feedback_correct : "res/koiGame/PlayingKoi/graphics/feedback/feedback_correct.png",
		feedback_empty : "res/koiGame/PlayingKoi/graphics/feedback/feedback_empty.png",
		feedback_incorrect : "res/koiGame/PlayingKoi/graphics/feedback/feedback_incorrect.png",


		ripple : "res/koiGame/PlayingKoi/graphics/occluders/ripple.png",

		foodEaten_png : "res/koiGame/food/foodEaten.png",
		foodEaten_plist : "res/koiGame/food/foodEaten.plist",

		koiSwim_png : "res/koiGame/koi/koiSwim.png",
		//koiSwim_json : "res/koiGame/koi/koiSwim.json",
		koiSwim_plist : "res/koiGame/koi/koiSwim.plist",

		BottomFeeder_png : "res/koiGame/distractors/bottomFeeder/BottomFeeder.png",
		BottomFeeder_plist : "res/koiGame/distractors/bottomFeeder/BottomFeeder.plist",

		DragonFly_png : "res/koiGame/distractors/dragonfly/DragonFly.png",
		DragonFly_json : "res/koiGame/distractors/dragonfly/DragonFly.json",
		DragonFly_plist : "res/koiGame/distractors/dragonfly/DragonFly.plist",

		Firefly_png : "res/koiGame/distractors/firefly/Firefly.png",
		Firefly_plist : "res/koiGame/distractors/firefly/Firefly.plist",

		Raindrop_png : "res/koiGame/distractors/raindrop/Raindrop.png",
		Raindrop_plist : "res/koiGame/distractors/raindrop/Raindrop.plist",


		fish_vsh  : "res/koiGame/Shaders/fish.vsh",
		fish1_fsh : "res/koiGame/Shaders/fish1.fsh",
		fish2_fsh : "res/koiGame/Shaders/fish2.fsh",
		fish3_fsh : "res/koiGame/Shaders/fish3.fsh",
		fish4_fsh : "res/koiGame/Shaders/fish4.fsh",
		fish5_fsh : "res/koiGame/Shaders/fish5.fsh",

		menuButtonBackgroundUp : "res/koiGame/buttons/menuButtonBackgroundUp.png",
		menuButtonBackgroundDown : "res/koiGame/buttons/menuButtonBackgroundDown.png",
		game_buttonPauseDown : "res/koiGame/buttons/game_buttonPauseDown.png",
		game_buttonPauseOff : "res/koiGame/buttons/game_buttonPauseOff.png",
	},
};

var g_resources = [];
for (var i in res) {
	if(typeof(res[i]) == "string"){
    	g_resources.push(res[i]);
	}
}

res.JsonPath = {
	koi_level : "res/Json/koi_level.json",
	settings : "res/Json/settings.json",
}