var first_test_pm_level_round = {
	"1001": {id : 1001,energy_level: -1, shown_time : 2,row_range: [3],column_range: [3],total_ele_num_range:[2],
        ele_type_num : 1,ele1_num_range:[2],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "1002": {id : 1002,energy_level: -1, shown_time : 2,row_range: [4],column_range: [3],total_ele_num_range:[3],
        ele_type_num : 1,ele1_num_range:[3],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "1003": {id : 1003,energy_level: 0, shown_time : 2,row_range: [4],column_range: [4],total_ele_num_range:[5],
        ele_type_num : 1,ele1_num_range:[5],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "1004": {id : 1004,energy_level: 0, shown_time : 2,row_range: [4],column_range: [4],total_ele_num_range:[6],
        ele_type_num : 1,ele1_num_range:[6],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "1005": {id : 1005,energy_level: 1, shown_time : 2,row_range: [5],column_range: [4],total_ele_num_range:[6,7],
        ele_type_num : 1,ele1_num_range:[6,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},

    "1006": {id : 1006,energy_level: 1, shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[6,7],
        ele_type_num : 1,ele1_num_range:[6,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "1007": {id : 1007,energy_level: 2, shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[9,10],
        ele_type_num : 1,ele1_num_range:[6,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "1008": {id : 1008,energy_level: 2, shown_time : 2,row_range: [5],column_range: [4],total_ele_num_range:[8,9],
        ele_type_num : 1,ele1_num_range:[5,6],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "1009": {id : 1009,energy_level: 3, shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[9,10],
        ele_type_num : 2,ele1_num_range:[5,6],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1010": {id : 1010,energy_level: 3, shown_time : 2,row_range: [6],column_range: [5],total_ele_num_range:[8,9],
        ele_type_num : 1,ele1_num_range:[6,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},

    "1011": {id : 1011,energy_level: 4, shown_time : 2,row_range: [6],column_range: [5],total_ele_num_range:[10,11],
        ele_type_num : 2,ele1_num_range:[6,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1012": {id : 1012,energy_level: 4, shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[11,12],
        ele_type_num : 1,ele1_num_range:[8,9],ele2_num_range:[0],overlap_num : 1,
        target: {desc:'',target_list:[1],target_num : 1}},
}