var first_test_nc_level = {
	1:{
        id:1,
        round_level: [
        	{
        		energy_level:-1,
		        level_tips:"",
		        pass_equation:3,
		        single_number_max:5,
		        cell_drop_time:1.5,
		        target_result:{min_value:6,max_value:10},
		        equation:{count:0,drop_way:[],typeIndex:[]},
		        bar_remove:{count:0,drop_way:0},
		        bar_not_remove:{count:0,drop_way:0}
		    },
		    {
        		energy_level:0,
		        level_tips:"",
		        pass_equation:6,
		        single_number_max:5,
		        cell_drop_time:1.5,
		        target_result:{min_value:6,max_value:15},
		        equation:{count:0,drop_way:[],typeIndex:[]},
		        bar_remove:{count:0,drop_way:0},
		        bar_not_remove:{count:0,drop_way:0}
		    },
		    {
        		energy_level:1,
		        level_tips:"5以内加减法",
		        pass_equation:9,
		        single_number_max:9,
		        cell_drop_time:1.5,
		        target_result:{min_value:10,max_value:20},
		        equation:{count:1,drop_way:[6],typeIndex:[1,2]},
		        bar_remove:{count:0,drop_way:0},
		        bar_not_remove:{count:0,drop_way:0}
		    },
		    {
        		energy_level:2,
		        level_tips:"6-10加减法",
		        pass_equation:12,
		        single_number_max:12,
		        cell_drop_time:1.3,
		        target_result:{min_value:15,max_value:20},
		        equation:{count:1,drop_way:[9],typeIndex:[3,4]},
		        bar_remove:{count:0,drop_way:0},
		        bar_not_remove:{count:0,drop_way:0}
		    },
		    {
        		energy_level:3,
		        level_tips:"20以内进位加法",
		        pass_equation:15,
		        single_number_max:15,
		        cell_drop_time:1.2,
		        target_result:{min_value:20,max_value:25},
		        equation:{count:2,drop_way:[12,13],typeIndex:[5,6,7]},
		        bar_remove:{count:3,drop_way:1},
		        bar_not_remove:{count:0,drop_way:0}
		    },
		    {
        		energy_level:4,
		        level_tips:"20以内退位减法",
		        pass_equation:18,
		        single_number_max:15,
		        cell_drop_time:1.2,
		        target_result:{min_value:20,max_value:30},
		        equation:{count:3,drop_way:[15,16,17],typeIndex:[8,9,10]},
		        bar_remove:{count:3,drop_way:1},
		        bar_not_remove:{count:0,drop_way:0}
		    }
        ]
    }
}