
var test_pm_level_round = {
    "10101": {id : 10101,shown_time : 2,row_range: [3],column_range: [3],total_ele_num_range:[2],
        ele_type_num : 1,ele1_num_range:[2],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "10102": {id : 10102,shown_time : 2,row_range: [3],column_range: [3],total_ele_num_range:[3],
        ele_type_num : 1,ele1_num_range:[3],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "10103": {id : 10103,shown_time : 2,row_range: [4],column_range: [3],total_ele_num_range:[4],
        ele_type_num : 1,ele1_num_range:[4],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "10104": {id : 10104,shown_time : 2,row_range: [4],column_range: [3],total_ele_num_range:[5],
        ele_type_num : 1,ele1_num_range:[5],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "10105": {id : 10105,shown_time : 2,row_range: [4],column_range: [3],total_ele_num_range:[6],
        ele_type_num : 1,ele1_num_range:[6],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},

	"11001": {id : 11001,shown_time : 2,row_range: [4],column_range: [3],total_ele_num_range:[3],
        ele_type_num : 1,ele1_num_range:[3],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "11002": {id : 11002,shown_time : 2,row_range: [4],column_range: [3],total_ele_num_range:[4],
        ele_type_num : 1,ele1_num_range:[4],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "11003": {id : 11003,shown_time : 2,row_range: [4],column_range: [3],total_ele_num_range:[5],
        ele_type_num : 1,ele1_num_range:[5],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "11004": {id : 11004,shown_time : 2,row_range: [4],column_range: [4],total_ele_num_range:[6],
        ele_type_num : 1,ele1_num_range:[6],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "11005": {id : 11005,shown_time : 2,row_range: [4],column_range: [4],total_ele_num_range:[7],
        ele_type_num : 1,ele1_num_range:[7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "101": {id : 101,shown_time : 2,row_range: [5],column_range: [4],total_ele_num_range:[5],
        ele_type_num : 1,ele1_num_range:[5],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "102": {id : 102,shown_time : 2,row_range: [5],column_range: [4],total_ele_num_range:[6,7],
        ele_type_num : 1,ele1_num_range:[6,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "103": {id : 103,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[6,7],
        ele_type_num : 1,ele1_num_range:[6,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "104": {id : 104,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[7,8],
        ele_type_num : 1,ele1_num_range:[7,8],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "105": {id : 105,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[8,9],
        ele_type_num : 1,ele1_num_range:[8,9],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "201": {id : 201,shown_time : 2,row_range: [5],column_range: [4],total_ele_num_range:[7,8],
        ele_type_num : 1,ele1_num_range:[7,8],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "202": {id : 202,shown_time : 2,row_range: [5],column_range: [4],total_ele_num_range:[9,10],
        ele_type_num : 1,ele1_num_range:[9,10],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "203": {id : 203,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[9,10],
        ele_type_num : 1,ele1_num_range:[9,10],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "204": {id : 204,shown_time : 2,row_range: [5],column_range: [4],total_ele_num_range:[8,9],
        ele_type_num : 2,ele1_num_range:[5,6],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "205": {id : 205,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[9,10],
        ele_type_num : 2,ele1_num_range:[5,6],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "301": {id : 301,shown_time : 2,row_range: [5],column_range: [4],total_ele_num_range:[9,10],
        ele_type_num : 2,ele1_num_range:[6,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "302": {id : 302,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[9,10],
        ele_type_num : 2,ele1_num_range:[5,6],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "303": {id : 303,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[10,11],
        ele_type_num : 2,ele1_num_range:[6,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "304": {id : 304,shown_time : 2,row_range: [6],column_range: [5],total_ele_num_range:[8,9],
        ele_type_num : 2,ele1_num_range:[6,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "305": {id : 305,shown_time : 2,row_range: [6],column_range: [5],total_ele_num_range:[10,11],
        ele_type_num : 2,ele1_num_range:[6,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "401": {id : 401,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[11],
        ele_type_num : 2,ele1_num_range:[8],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "402": {id : 402,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[10,11],
        ele_type_num : 2,ele1_num_range:[6,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "403": {id : 403,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[11,12],
        ele_type_num : 2,ele1_num_range:[8,9],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "404": {id : 404,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[10,11],
        ele_type_num : 2,ele1_num_range:[7,8],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "405": {id : 405,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[11,12],
        ele_type_num : 2,ele1_num_range:[8,9],ele2_num_range:[0],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "501": {id : 501,shown_time : 2,row_range: [5],column_range: [4],total_ele_num_range:[10],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[2],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "502": {id : 502,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[10,11],
        ele_type_num : 3,ele1_num_range:[6,7],ele2_num_range:[2],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "503": {id : 503,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[12,13],
        ele_type_num : 3,ele1_num_range:[8,9],ele2_num_range:[2],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "504": {id : 504,shown_time : 2,row_range: [6],column_range: [5],total_ele_num_range:[12,13],
        ele_type_num : 3,ele1_num_range:[8,9],ele2_num_range:[2],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "505": {id : 505,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[13,14],
        ele_type_num : 3,ele1_num_range:[9,10],ele2_num_range:[3],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "601": {id : 601,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[13],
        ele_type_num : 2,ele1_num_range:[9,10],ele2_num_range:[0],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "602": {id : 602,shown_time : 2,row_range: [6],column_range: [5],total_ele_num_range:[13,14],
        ele_type_num : 2,ele1_num_range:[8,9],ele2_num_range:[0],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "603": {id : 603,shown_time : 2,row_range: [6],column_range: [5],total_ele_num_range:[15,16],
        ele_type_num : 3,ele1_num_range:[8,9],ele2_num_range:[3,4],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1],target_num : 1}},
    "604": {id : 604,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[15,16],
        ele_type_num : 2,ele1_num_range:[8,9],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "605": {id : 605,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[15,16],
        ele_type_num : 3,ele1_num_range:[7,8],ele2_num_range:[4,5],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "701": {id : 701,shown_time : 2,row_range: [5],column_range: [4],total_ele_num_range:[12],
        ele_type_num : 3,ele1_num_range:[4,5],ele2_num_range:[4,5],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[2,3],target_num : 1}},
    "702": {id : 702,shown_time : 2,row_range: [5],column_range: [4],total_ele_num_range:[13,14],
        ele_type_num : 3,ele1_num_range:[7],ele2_num_range:[3,4],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "703": {id : 703,shown_time : 2,row_range: [5],column_range: [4],total_ele_num_range:[13,14],
        ele_type_num : 3,ele1_num_range:[5,6],ele2_num_range:[4,5],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "704": {id : 704,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[15,16],
        ele_type_num : 3,ele1_num_range:[8,9],ele2_num_range:[4,5],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "705": {id : 705,shown_time : 2,row_range: [6],column_range: [5],total_ele_num_range:[16,17],
        ele_type_num : 3,ele1_num_range:[8,9],ele2_num_range:[5,6],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "801": {id : 801,shown_time : 2,row_range: [6],column_range: [5],total_ele_num_range:[16],
        ele_type_num : 3,ele1_num_range:[8],ele2_num_range:[4,5],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "802": {id : 802,shown_time : 2,row_range: [6],column_range: [5],total_ele_num_range:[16,17],
        ele_type_num : 3,ele1_num_range:[8],ele2_num_range:[5,6],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "803": {id : 803,shown_time : 2,row_range: [6],column_range: [5],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[7,8],ele2_num_range:[6,7],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "804": {id : 804,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[6,7],ele2_num_range:[7,8],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "805": {id : 805,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[6,7],ele2_num_range:[6,7],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "901": {id : 901,shown_time : 2,row_range: [6],column_range: [5],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[4,5],ele2_num_range:[2],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "902": {id : 902,shown_time : 2,row_range: [6],column_range: [5],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[5,6],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "903": {id : 903,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[16],
        ele_type_num : 1,ele1_num_range:[6],ele2_num_range:[6,7],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "904": {id : 904,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[6,7],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "905": {id : 905,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[5,6],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1001": {id : 1001,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[2],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1002": {id : 1002,shown_time : 2,row_range: [6],column_range: [5],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[5],ele2_num_range:[5,6],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1003": {id : 1003,shown_time : 2,row_range: [6],column_range: [5],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[5,6],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1004": {id : 1004,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[5],ele2_num_range:[5,6],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1005": {id : 1005,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[6],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
}