
//单向：1  双向：2  空：0

var test_sm_level = {
	1 : {
    	id : 1,
    	energy_level : -1,
		channal_count : 1,
		fish_count : {minCount : 40, maxCount : 50},
		fish_type : {fish_type_count : 3, color_type : 3, pic_type : 3},
		show_fish_number : 3,
		fish_goal_probability : {member : 9, denominator : 20},
		show_fish_height : 2,
		channal12_width : 650,
		fish_change_probability : {member : 1, denominator : 20},
		fish_direction_count : {channal1 : 1, channal2 : 0, channal3 : 0, channal4 : 0}
    },
	2 : {
    	id : 2,
    	energy_level : 0,
		channal_count : 1,
		fish_count : {minCount : 50, maxCount : 70},
		fish_type : {fish_type_count : 3, color_type : 3, pic_type : 3},
		show_fish_number : 4,
		fish_goal_probability : {member : 9, denominator : 20},
		show_fish_height : 3,
		channal12_width : 600,
		fish_change_probability : {member : 1, denominator : 17},
		fish_direction_count : {channal1 : 2, channal2 : 0, channal3 : 0, channal4 : 0}
    },
    3 : {
    	id : 3,
    	energy_level : 1,
		channal_count : 2,
		fish_count : {minCount : 80, maxCount : 100},
		fish_type : {fish_type_count : 3, color_type : 2, pic_type : 3},
		show_fish_number : 5,
		fish_goal_probability : {member : 8, denominator : 17},
		show_fish_height : 2,
		channal12_width : 600,
		fish_change_probability : {member : 1, denominator : 14},
		fish_direction_count : {channal1 : 1, channal2 : 1, channal3 : 0, channal4 : 0}
    },
    4 : {
    	id : 4,
    	energy_level : 2,
		channal_count : 3,
		fish_count : {minCount : 115, maxCount : 135},
		fish_type : {fish_type_count : 4, color_type : 3, pic_type : 3},
		show_fish_number : 5,
		fish_goal_probability : {member : 10, denominator : 21},
		show_fish_height : 3,
		channal12_width : 570,
		fish_change_probability : {member : 1, denominator : 13},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 0}
    },	
    5 : {
    	id : 5,
    	energy_level : 3,
		channal_count : 4,
		fish_count : {minCount : 145, maxCount : 165},
		fish_type : {fish_type_count : 4, color_type : 1, pic_type : 4},
		show_fish_number : 5,
		fish_goal_probability : {member : 4, denominator : 7},
		show_fish_height : 3,
		channal12_width : 540,
		fish_change_probability : {member : 1, denominator : 9},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },	
    6 : {
    	id : 6,
    	energy_level : 4,
		channal_count : 4,
		fish_count : {minCount : 160, maxCount : 180},
		fish_type : {fish_type_count : 5, color_type : 4, pic_type : 3},
		show_fish_number : 5,
		fish_goal_probability : {member : 7, denominator : 15},
		show_fish_height : 3,
		channal12_width : 540,
		fish_change_probability : {member : 1, denominator : 10},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },	
    7 : {
    	id : 7,
    	energy_level : 5,
		channal_count : 4,
		fish_count : {minCount : 180, maxCount : 200},
		fish_type : {fish_type_count : 5, color_type : 3, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 10, denominator : 21},
		show_fish_height : 3,
		channal12_width : 510,
		fish_change_probability : {member : 1, denominator : 9},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },	
    8 : {
    	id : 8,
    	energy_level : 6,
		channal_count : 4,
		fish_count : {minCount : 210, maxCount : 230},
		fish_type : {fish_type_count : 5, color_type : 1, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 11, denominator : 21},
		show_fish_height : 3,
		channal12_width : 480,
		fish_change_probability : {member : 1, denominator : 9},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },	
    9 : {
    	id : 9,
    	energy_level : 7,
		channal_count : 4,
		fish_count : {minCount : 220, maxCount : 240},
		fish_type : {fish_type_count : 5, color_type : 1, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 9, denominator : 19},
		show_fish_height : 3,
		channal12_width : 450,
		fish_change_probability : {member : 1, denominator : 9},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },	
    10 : {
    	id : 10,
    	energy_level : 8,
		channal_count : 4,
		fish_count : {minCount : 240, maxCount : 265},
		fish_type : {fish_type_count : 5, color_type : 1, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 8, denominator : 15},
		show_fish_height : 3,
		channal12_width : 420,
		fish_change_probability : {member : 1, denominator : 10},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },	
    11 : {
    	id : 11,
    	energy_level : 9,
		channal_count : 4,
		fish_count : {minCount : 250, maxCount : 280},
		fish_type : {fish_type_count : 5, color_type : 1, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 11, denominator : 21},
		show_fish_height : 3,
		channal12_width : 420,
		fish_change_probability : {member : 1, denominator : 12},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },	
    12 : {
    	id : 12,
    	energy_level : 10,
		channal_count : 4,
		fish_count : {minCount : 260, maxCount : 300},
		fish_type : {fish_type_count : 5, color_type : 1, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 9, denominator : 20},
		show_fish_height : 3,
		channal12_width : 400,
		fish_change_probability : {member : 1, denominator : 11},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
}