var test_cm_level = {
    1:{
        id:1,
        energy_level:-1,
        limit_time:35,
        pass_count:10,
        fontcolor_count:3,
        colorwords_count:0,
        bg_piece_color_count:3,
        play_type:1
    },
	2:{
        id:2,
        energy_level:0,
        limit_time:37,
        pass_count:14,
        fontcolor_count:5,
        colorwords_count:0,
        bg_piece_color_count:5,
        play_type:1
    },
    3:{
        id:3,
        energy_level:1,
        limit_time:39,
        pass_count:18,
        fontcolor_count:6,
        colorwords_count:0,
        bg_piece_color_count:6,
        play_type:1
    },
    4:{
        id:4,
        energy_level:2,
        limit_time:48,
        pass_count:27,
        fontcolor_count:4,
        colorwords_count:4,
        bg_piece_color_count:0,
        play_type:2
    },
    5:{
        id:5,
        energy_level:3,
        limit_time:32,
        pass_count:14,
        fontcolor_count:4,
        colorwords_count:4,
        bg_piece_color_count:0,
        play_type:2
    },
    6:{
        id:6,
        energy_level:4,
        limit_time:36,
        pass_count:14,
        fontcolor_count:0,
        colorwords_count:5,
        bg_piece_color_count:5,
        play_type:3
    },
    7:{
        id:7,
        energy_level:5,
        limit_time:60,
        pass_count:42,
        fontcolor_count:0,
        colorwords_count:6,
        bg_piece_color_count:6,
        play_type:3
    },
    8:{
        id:8,
        energy_level:6,
        limit_time:66,
        pass_count:52,
        fontcolor_count:0,
        colorwords_count:6,
        bg_piece_color_count:7,
        play_type:3
    },
    9:{
        id:9,
        energy_level:7,
        limit_time:70,
        pass_count:54,
        fontcolor_count:7,
        colorwords_count:7,
        bg_piece_color_count:0,
        play_type:4
    },
    10:{
        id:10,
        energy_level:8,
        limit_time:70,
        pass_count:58,
        fontcolor_count:7,
        colorwords_count:7,
        bg_piece_color_count:0,
        play_type:4
    },
    11:{
        id:11,
        energy_level:9,
        limit_time:70,
        pass_count:64,
        fontcolor_count:7,
        colorwords_count:7,
        bg_piece_color_count:0,
        play_type:4
    },
    12:{
        id:12,
        energy_level:10,
        limit_time:70,
        pass_count:70,
        fontcolor_count:7,
        colorwords_count:7,
        bg_piece_color_count:0,
        play_type:4
    },
}