
var pm_tip_config = {
	tip : '请找出所有此图标',
}

var dict_pm_level_round = {
    "10000": {id : 10000,shown_time : 2,row_range: [3],column_range: [3],total_ele_num_range:[2],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "10001": {id : 10001,shown_time : 2,row_range: [3],column_range: [3,4],total_ele_num_range:[3,5],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},

    "101": {id : 101,shown_time : 2,row_range: [3],column_range: [3],total_ele_num_range:[2],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "102": {id : 102,shown_time : 2,row_range: [3],column_range: [3,4],total_ele_num_range:[3,5],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "103": {id : 103,shown_time : 2,row_range: [3],column_range: [3,4],total_ele_num_range:[3,5],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0,1],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "104": {id : 104,shown_time : 2,row_range: [3],column_range: [3,4],total_ele_num_range:[3,5],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "105": {id : 105,shown_time : 2,row_range: [3],column_range: [3,4],total_ele_num_range:[3,5],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "106": {id : 106,shown_time : 2,row_range: [3],column_range: [4],total_ele_num_range:[4,5],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},

    "201": {id : 201,shown_time : 2,row_range: [3],column_range: [4],total_ele_num_range:[3],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "202": {id : 202,shown_time : 2,row_range: [3,4],column_range: [4],total_ele_num_range:[4,5],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "203": {id : 203,shown_time : 2,row_range: [3,4],column_range: [4],total_ele_num_range:[4,5],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0,1],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "204": {id : 204,shown_time : 2,row_range: [3,4],column_range: [4],total_ele_num_range:[4,5],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "205": {id : 205,shown_time : 2,row_range: [3,4],column_range: [4],total_ele_num_range:[4,5],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "206": {id : 206,shown_time : 2,row_range: [3,4],column_range: [4],total_ele_num_range:[4,5],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "207": {id : 207,shown_time : 2,row_range: [4],column_range: [4],total_ele_num_range:[5,6],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},


    "301": {id : 301,shown_time : 2,row_range: [4],column_range: [4],total_ele_num_range:[4],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "302": {id : 302,shown_time : 2,row_range: [4],column_range: [4,5],total_ele_num_range:[4,6],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "303": {id : 303,shown_time : 2,row_range: [4],column_range: [4,5],total_ele_num_range:[4,6],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0,1],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "304": {id : 304,shown_time : 2,row_range: [4],column_range: [4,5],total_ele_num_range:[4,6],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "305": {id : 305,shown_time : 2,row_range: [4],column_range: [4,5],total_ele_num_range:[4,6],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "306": {id : 306,shown_time : 2,row_range: [4],column_range: [4,5],total_ele_num_range:[4,6],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "307": {id : 307,shown_time : 2,row_range: [4],column_range: [5],total_ele_num_range:[6,7],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},


    "401": {id : 401,shown_time : 2,row_range: [4],column_range: [5],total_ele_num_range:[5],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "402": {id : 402,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[5,7],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "403": {id : 403,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[5,7],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0,1],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "404": {id : 404,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[5,7],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "405": {id : 405,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[5,7],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "406": {id : 406,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[5,7],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "407": {id : 407,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[7,8],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},

    "501": {id : 501,shown_time : 2,row_range: [4],column_range: [5],total_ele_num_range:[6],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "502": {id : 502,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[7,8],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "503": {id : 503,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[7,8],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0,1],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "504": {id : 504,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[7,8],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "505": {id : 505,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[7,8],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "506": {id : 506,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[7,8],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "507": {id : 507,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[8,9],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},

    "601": {id : 601,shown_time : 2,row_range: [4],column_range: [5],total_ele_num_range:[7],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "602": {id : 602,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[8,10],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "603": {id : 603,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[8,10],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0,1],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "604": {id : 604,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[6,8],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "605": {id : 605,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[8,10],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "606": {id : 606,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[8,10],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "607": {id : 607,shown_time : 2,row_range: [5],column_range: [6],total_ele_num_range:[6,8],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},


    "701": {id : 701,shown_time : 2,row_range: [4],column_range: [5],total_ele_num_range:[8],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "702": {id : 702,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[9,10],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "703": {id : 703,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[9,10],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "704": {id : 704,shown_time : 2,row_range: [5],column_range: [5,6],total_ele_num_range:[11,12],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "705": {id : 705,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[8,9],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "706": {id : 706,shown_time : 2,row_range: [5],column_range: [5,6],total_ele_num_range:[11,12],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "707": {id : 707,shown_time : 2,row_range: [5],column_range: [6],total_ele_num_range:[12],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},


    "801": {id : 801,shown_time : 2,row_range: [4],column_range: [5],total_ele_num_range:[8],
        ele_type_num : 2,ele1_num_range:[6],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "802": {id : 802,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[8],
        ele_type_num : 2,ele1_num_range:[5,6],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "803": {id : 803,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[9],
        ele_type_num : 2,ele1_num_range:[5,6],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "804": {id : 804,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[9],
        ele_type_num : 2,ele1_num_range:[5,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "805": {id : 805,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[10],
        ele_type_num : 2,ele1_num_range:[5,8],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "806": {id : 806,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[10],
        ele_type_num : 2,ele1_num_range:[6,8],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "807": {id : 807,shown_time : 2,row_range: [5],column_range: [6],total_ele_num_range:[10],
        ele_type_num : 2,ele1_num_range:[7,8],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},


    "901": {id : 901,shown_time : 2,row_range: [4],column_range: [5],total_ele_num_range:[9],
        ele_type_num : 2,ele1_num_range:[6,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "902": {id : 902,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[9],
        ele_type_num : 2,ele1_num_range:[5,6],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "903": {id : 903,shown_time : 2,row_range: [4,5],column_range: [5],total_ele_num_range:[10],
        ele_type_num : 2,ele1_num_range:[5,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "904": {id : 904,shown_time : 2,row_range: [5],column_range: [5,6],total_ele_num_range:[10],
        ele_type_num : 2,ele1_num_range:[6,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "905": {id : 905,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[9],
        ele_type_num : 2,ele1_num_range:[4,6],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "906": {id : 906,shown_time : 2,row_range: [5],column_range: [5,6],total_ele_num_range:[11],
        ele_type_num : 2,ele1_num_range:[5,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "907": {id : 907,shown_time : 2,row_range: [5],column_range: [6],total_ele_num_range:[11],
        ele_type_num : 2,ele1_num_range:[7,8],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},

    "1001": {id : 1001,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[9],
        ele_type_num : 2,ele1_num_range:[6,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1002": {id : 1002,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[8],
        ele_type_num : 2,ele1_num_range:[5,6],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1003": {id : 1003,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[9],
        ele_type_num : 2,ele1_num_range:[5,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1004": {id : 1004,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[10],
        ele_type_num : 2,ele1_num_range:[5,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1005": {id : 1005,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[10],
        ele_type_num : 2,ele1_num_range:[6,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1006": {id : 1006,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[11],
        ele_type_num : 2,ele1_num_range:[5,7],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1007": {id : 1007,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[11],
        ele_type_num : 2,ele1_num_range:[7,8],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
            
    "1101": {id : 1101,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[10],
        ele_type_num : 2,ele1_num_range:[7,8],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1102": {id : 1102,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[9],
        ele_type_num : 2,ele1_num_range:[6,8],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1103": {id : 1103,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[10],
        ele_type_num : 2,ele1_num_range:[6,8],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1104": {id : 1104,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[11],
        ele_type_num : 2,ele1_num_range:[6,9],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1105": {id : 1105,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[11],
        ele_type_num : 2,ele1_num_range:[7,9],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1106": {id : 1106,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[12],
        ele_type_num : 2,ele1_num_range:[7,9],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1107": {id : 1107,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[12],
        ele_type_num : 2,ele1_num_range:[8,9],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},

    "1201": {id : 1201,shown_time : 2,row_range: [5],column_range: [5],total_ele_num_range:[11],
        ele_type_num : 2,ele1_num_range:[8],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1202": {id : 1202,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[10],
        ele_type_num : 2,ele1_num_range:[6,8],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1203": {id : 1203,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[11],
        ele_type_num : 2,ele1_num_range:[7,8],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1204": {id : 1204,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[11],
        ele_type_num : 2,ele1_num_range:[7,9],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1205": {id : 1205,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[12],
        ele_type_num : 2,ele1_num_range:[7,8],ele2_num_range:[0],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1206": {id : 1206,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[12],
        ele_type_num : 2,ele1_num_range:[7,9],ele2_num_range:[0],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1207": {id : 1207,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[12],
        ele_type_num : 2,ele1_num_range:[8,9],ele2_num_range:[0],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},


    "1301": {id : 1301,shown_time : 2,row_range: [4],column_range: [4],total_ele_num_range:[12],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "1302": {id : 1302,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[10],
        ele_type_num : 2,ele1_num_range:[7,8],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1303": {id : 1303,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[11],
        ele_type_num : 2,ele1_num_range:[7,8],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1304": {id : 1304,shown_time : 2,row_range: [4],column_range: [5],total_ele_num_range:[10],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[2,3],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1305": {id : 1305,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[10],
        ele_type_num : 2,ele1_num_range:[7,8],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1306": {id : 1306,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[11],
        ele_type_num : 2,ele1_num_range:[7,8],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1307": {id : 1307,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[12],
        ele_type_num : 2,ele1_num_range:[8,9],ele2_num_range:[0],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},


    "1401": {id : 1401,shown_time : 2,row_range: [4],column_range: [5],total_ele_num_range:[16],
        ele_type_num : 2,ele1_num_range:[14],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1402": {id : 1402,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[11],
        ele_type_num : 2,ele1_num_range:[7,8],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1403": {id : 1403,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[12],
        ele_type_num : 2,ele1_num_range:[7,8],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1404": {id : 1404,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[12],
        ele_type_num : 3,ele1_num_range:[7,9],ele2_num_range:[2],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1405": {id : 1405,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[13],
        ele_type_num : 2,ele1_num_range:[7,9],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1406": {id : 1406,shown_time : 2,row_range: [5,6],column_range: [6],total_ele_num_range:[13],
        ele_type_num : 2,ele1_num_range:[8,9],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1407": {id : 1407,shown_time : 2,row_range: [6],column_range: [6],total_ele_num_range:[33],
        ele_type_num : 2,ele1_num_range:[29,30],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},


    "1501": {id : 1501,shown_time : 2.5,row_range: [4],column_range: [5],total_ele_num_range:[10],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[2],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1502": {id : 1502,shown_time : 2.5,row_range: [5],column_range: [5],total_ele_num_range:[10],
        ele_type_num : 3,ele1_num_range:[6,7],ele2_num_range:[2],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1503": {id : 1503,shown_time : 2.5,row_range: [5],column_range: [5],total_ele_num_range:[20],
        ele_type_num : 3,ele1_num_range:[16],ele2_num_range:[1,2],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1504": {id : 1504,shown_time : 2.5,row_range: [5],column_range: [5],total_ele_num_range:[11],
        ele_type_num : 3,ele1_num_range:[7,8],ele2_num_range:[2],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1505": {id : 1505,shown_time : 2.5,row_range: [5],column_range: [5],total_ele_num_range:[12],
        ele_type_num : 3,ele1_num_range:[7,8],ele2_num_range:[2],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1506": {id : 1506,shown_time : 2.5,row_range: [5],column_range: [5],total_ele_num_range:[12],
        ele_type_num : 3,ele1_num_range:[7,9],ele2_num_range:[2],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1507": {id : 1507,shown_time : 2.5,row_range: [5],column_range: [5],total_ele_num_range:[13],
        ele_type_num : 3,ele1_num_range:[6,8],ele2_num_range:[2],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},


    "1601": {id : 1601,shown_time : 2.5,row_range: [5],column_range: [5],total_ele_num_range:[12],
        ele_type_num : 2,ele1_num_range:[9,10],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1602": {id : 1602,shown_time : 2.5,row_range: [5],column_range: [5,6],total_ele_num_range:[12],
        ele_type_num : 3,ele1_num_range:[8,9],ele2_num_range:[2],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1603": {id : 1603,shown_time : 2.5,row_range: [5],column_range: [5,6],total_ele_num_range:[13],
        ele_type_num : 3,ele1_num_range:[8,9],ele2_num_range:[2],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1604": {id : 1604,shown_time : 2.5,row_range: [5],column_range: [5,6],total_ele_num_range:[13],
        ele_type_num : 3,ele1_num_range:[9,10],ele2_num_range:[2],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1605": {id : 1605,shown_time : 2.5,row_range: [5],column_range: [5,6],total_ele_num_range:[14],
        ele_type_num : 3,ele1_num_range:[8,9],ele2_num_range:[2,3],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1606": {id : 1606,shown_time : 2.5,row_range: [5],column_range: [5,6],total_ele_num_range:[14],
        ele_type_num : 3,ele1_num_range:[9,10],ele2_num_range:[2,3],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1607": {id : 1607,shown_time : 2.5,row_range: [5],column_range: [6],total_ele_num_range:[15],
        ele_type_num : 3,ele1_num_range:[9,10],ele2_num_range:[2,3],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},


    "1701": {id : 1701,shown_time : 2.5,row_range: [5],column_range: [6],total_ele_num_range:[22],
        ele_type_num : 1,ele1_num_range:[0],ele2_num_range:[0],overlap_num : 0,
        target: {desc:'',target_list:[1],target_num : 1}},
    "1702": {id : 1702,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[12],
        ele_type_num : 3,ele1_num_range:[8,9],ele2_num_range:[2],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1703": {id : 1703,shown_time : 2.5,row_range: [5],column_range: [5],total_ele_num_range:[10],
        ele_type_num : 3,ele1_num_range:[6,7],ele2_num_range:[2],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1704": {id : 1704,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[13],
        ele_type_num : 3,ele1_num_range:[8,10],ele2_num_range:[2],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1705": {id : 1705,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[14],
        ele_type_num : 3,ele1_num_range:[8,9],ele2_num_range:[2,3],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1706": {id : 1706,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[14],
        ele_type_num : 3,ele1_num_range:[9,10],ele2_num_range:[2],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1707": {id : 1707,shown_time : 2.5,row_range: [6],column_range: [6],total_ele_num_range:[15],
        ele_type_num : 3,ele1_num_range:[9,10],ele2_num_range:[3,4],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},


    "1801": {id : 1801,shown_time : 2.5,row_range: [5],column_range: [5],total_ele_num_range:[12],
        ele_type_num : 2,ele1_num_range:[8,9],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1802": {id : 1802,shown_time : 2.5,row_range: [5],column_range: [5,6],total_ele_num_range:[12],
        ele_type_num : 2,ele1_num_range:[9,10],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1803": {id : 1803,shown_time : 2.5,row_range: [5],column_range: [5,6],total_ele_num_range:[13],
        ele_type_num : 2,ele1_num_range:[9,10],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1804": {id : 1804,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[14],
        ele_type_num : 3,ele1_num_range:[9,10],ele2_num_range:[2,3],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[2,3],target_num : 1}},
    "1805": {id : 1805,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[15],
        ele_type_num : 3,ele1_num_range:[9,10],ele2_num_range:[3],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[2,3],target_num : 1}},
    "1806": {id : 1806,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[15],
        ele_type_num : 3,ele1_num_range:[9,10],ele2_num_range:[3,4],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[2,3],target_num : 1}},
    "1807": {id : 1807,shown_time : 2.5,row_range: [6],column_range: [6],total_ele_num_range:[16],
        ele_type_num : 3,ele1_num_range:[9,10],ele2_num_range:[3,4],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[2,3],target_num : 1}},


    "1901": {id : 1901,shown_time : 2.5,row_range: [5],column_range: [5],total_ele_num_range:[13],
        ele_type_num : 2,ele1_num_range:[8,9],ele2_num_range:[0],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1902": {id : 1902,shown_time : 2.5,row_range: [5],column_range: [5,6],total_ele_num_range:[13],
        ele_type_num : 2,ele1_num_range:[8,9],ele2_num_range:[0],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1903": {id : 1903,shown_time : 2.5,row_range: [5],column_range: [5,6],total_ele_num_range:[14],
        ele_type_num : 2,ele1_num_range:[8,9],ele2_num_range:[0],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "1904": {id : 1904,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[14],
        ele_type_num : 3,ele1_num_range:[8,9],ele2_num_range:[3,4],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1905": {id : 1905,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[15],
        ele_type_num : 3,ele1_num_range:[8,9],ele2_num_range:[3,4],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[2,3],target_num : 1}},
    "1906": {id : 1906,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[15],
        ele_type_num : 3,ele1_num_range:[8,9],ele2_num_range:[5],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "1907": {id : 1907,shown_time : 2.5,row_range: [6],column_range: [6],total_ele_num_range:[16],
        ele_type_num : 3,ele1_num_range:[8,9],ele2_num_range:[3,4],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[2,3],target_num : 1}},


    "2001": {id : 2001,shown_time : 2.5,row_range: [5],column_range: [5],total_ele_num_range:[14],
        ele_type_num : 2,ele1_num_range:[8,9],ele2_num_range:[0],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "2002": {id : 2002,shown_time : 2.5,row_range: [5],column_range: [5,6],total_ele_num_range:[15],
        ele_type_num : 2,ele1_num_range:[7,9],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "2003": {id : 2003,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[16],
        ele_type_num : 3,ele1_num_range:[7,9],ele2_num_range:[2],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2004": {id : 2004,shown_time : 2.5,row_range: [5],column_range: [5,6],total_ele_num_range:[15],
        ele_type_num : 2,ele1_num_range:[7,9],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "2005": {id : 2005,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[16],
        ele_type_num : 2,ele1_num_range:[7,9],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "2006": {id : 2006,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[16],
        ele_type_num : 3,ele1_num_range:[7,9],ele2_num_range:[3,4],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[2,3],target_num : 1}},
    "2007": {id : 2007,shown_time : 2.5,row_range: [6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[7,9],ele2_num_range:[4,5],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},


    "2101": {id : 2101,shown_time : 2.5,row_range: [5],column_range: [6],total_ele_num_range:[15],
        ele_type_num : 2,ele1_num_range:[8,9],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "2102": {id : 2102,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[15],
        ele_type_num : 3,ele1_num_range:[7,9],ele2_num_range:[5],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2103": {id : 2103,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[16],
        ele_type_num : 2,ele1_num_range:[7,8],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "2104": {id : 2104,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[16],
        ele_type_num : 2,ele1_num_range:[7,9],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "2105": {id : 2105,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[7,9],ele2_num_range:[4,5],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2106": {id : 2106,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[7,8],ele2_num_range:[4,5],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[2,3],target_num : 1}},
    "2107": {id : 2107,shown_time : 2.5,row_range: [6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 2,ele1_num_range:[7,9],ele2_num_range:[0],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},


    "2201": {id : 2201,shown_time : 2.5,row_range: [5],column_range: [6],total_ele_num_range:[15],
        ele_type_num : 2,ele1_num_range:[9],ele2_num_range:[0],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "2202": {id : 2202,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[15],
        ele_type_num : 2,ele1_num_range:[8],ele2_num_range:[0],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "2203": {id : 2203,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[16],
        ele_type_num : 2,ele1_num_range:[8],ele2_num_range:[0],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "2204": {id : 2204,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[16],
        ele_type_num : 2,ele1_num_range:[7,8],ele2_num_range:[0],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "2205": {id : 2205,shown_time : 2.5,row_range: [5,6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 2,ele1_num_range:[8],ele2_num_range:[0],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "2206": {id : 2206,shown_time : 2.5,row_range: [6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 2,ele1_num_range:[8,9],ele2_num_range:[0],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "2207": {id : 2207,shown_time : 2.5,row_range: [6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 2,ele1_num_range:[9],ele2_num_range:[0],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},


    "2301": {id : 2301,shown_time : 3,row_range: [4,5],column_range: [5],total_ele_num_range:[12],
        ele_type_num : 3,ele1_num_range:[4,5],ele2_num_range:[4,5],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2302": {id : 2302,shown_time : 3,row_range: [4],column_range: [5],total_ele_num_range:[12],
        ele_type_num : 3,ele1_num_range:[4,5],ele2_num_range:[4,5],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[2,3],target_num : 1}},
    "2303": {id : 2303,shown_time : 3,row_range: [4,5],column_range: [5],total_ele_num_range:[12],
        ele_type_num : 3,ele1_num_range:[7],ele2_num_range:[3,4],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2304": {id : 2304,shown_time : 3,row_range: [4,5],column_range: [5],total_ele_num_range:[13],
        ele_type_num : 3,ele1_num_range:[7],ele2_num_range:[3,4],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2305": {id : 2305,shown_time : 3,row_range: [4,5],column_range: [5],total_ele_num_range:[13],
        ele_type_num : 3,ele1_num_range:[7],ele2_num_range:[4,5],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2306": {id : 2306,shown_time : 3,row_range: [4,5],column_range: [5],total_ele_num_range:[14],
        ele_type_num : 3,ele1_num_range:[7],ele2_num_range:[4,5],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2307": {id : 2307,shown_time : 3,row_range: [5],column_range: [5],total_ele_num_range:[14],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[4,5],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},



    "2401": {id : 2401,shown_time : 3,row_range: [4],column_range: [5],total_ele_num_range:[12],
        ele_type_num : 3,ele1_num_range:[4,5],ele2_num_range:[2],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[2,3],target_num : 1}},
    "2402": {id : 2402,shown_time : 3,row_range: [5],column_range: [5,6],total_ele_num_range:[13],
        ele_type_num : 3,ele1_num_range:[4,5],ele2_num_range:[4,5],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2403": {id : 2403,shown_time : 3,row_range: [5],column_range: [5,6],total_ele_num_range:[13],
        ele_type_num : 3,ele1_num_range:[5,6],ele2_num_range:[4,5],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2404": {id : 2404,shown_time : 3,row_range: [5],column_range: [5,6],total_ele_num_range:[14],
        ele_type_num : 3,ele1_num_range:[5,6],ele2_num_range:[4,5],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2405": {id : 2405,shown_time : 3,row_range: [5],column_range: [5,6],total_ele_num_range:[14],
        ele_type_num : 3,ele1_num_range:[5,6],ele2_num_range:[5,6],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2406": {id : 2406,shown_time : 3,row_range: [5],column_range: [5,6],total_ele_num_range:[15],
        ele_type_num : 3,ele1_num_range:[5,6],ele2_num_range:[5,6],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2407": {id : 2407,shown_time : 3,row_range: [5],column_range: [6],total_ele_num_range:[15],
        ele_type_num : 3,ele1_num_range:[5],ele2_num_range:[5],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},


    "2501": {id : 2501,shown_time : 3,row_range: [5],column_range: [5],total_ele_num_range:[16],
        ele_type_num : 3,ele1_num_range:[8],ele2_num_range:[4,5],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2502": {id : 2502,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[15],
        ele_type_num : 3,ele1_num_range:[9],ele2_num_range:[4,5],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2503": {id : 2503,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[16],
        ele_type_num : 3,ele1_num_range:[9],ele2_num_range:[4,5],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2504": {id : 2504,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[9],ele2_num_range:[4,5],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2505": {id : 2505,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[9],ele2_num_range:[5,6],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2506": {id : 2506,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[9],ele2_num_range:[5,6],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2507": {id : 2507,shown_time : 3,row_range: [6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[9],ele2_num_range:[6,7],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},


    "2601": {id : 2601,shown_time : 3,row_range: [5],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[8],ele2_num_range:[4,5],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2602": {id : 2602,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[8],ele2_num_range:[5,6],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2603": {id : 2603,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[8],ele2_num_range:[6,7],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2604": {id : 2604,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[8],ele2_num_range:[7,8],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2605": {id : 2605,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[8],ele2_num_range:[7,8],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2606": {id : 2606,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[8],ele2_num_range:[8,9],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2607": {id : 2607,shown_time : 3,row_range: [6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[8],ele2_num_range:[7,8],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},

    "2701": {id : 2701,shown_time : 3,row_range: [5],column_range: [6],total_ele_num_range:[9],
        ele_type_num : 2,ele1_num_range:[5],ele2_num_range:[0],overlap_num : 0,
        target: {desc:pm_tip_config.tip,target_list:[1,2],target_num : 1}},
    "2702": {id : 2702,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[7],ele2_num_range:[8,9],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2703": {id : 2703,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[8],ele2_num_range:[7,8],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2704": {id : 2704,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[7],ele2_num_range:[8,9],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2705": {id : 2705,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[7],ele2_num_range:[7,8],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2706": {id : 2706,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[7],ele2_num_range:[6,7],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2707": {id : 2707,shown_time : 3,row_range: [6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[7],ele2_num_range:[6,7],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},


    "2801": {id : 2801,shown_time : 3,row_range: [4],column_range: [4],total_ele_num_range:[10],
        ele_type_num : 3,ele1_num_range:[4,5],ele2_num_range:[2],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2802": {id : 2802,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[6,7],ele2_num_range:[7,8],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2803": {id : 2803,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[6,7],ele2_num_range:[6,7],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2804": {id : 2804,shown_time : 3,row_range: [5],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[6,7],ele2_num_range:[5,6],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2805": {id : 2805,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[6,7],ele2_num_range:[2],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2806": {id : 2806,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[6,7],ele2_num_range:[2],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2807": {id : 2807,shown_time : 3,row_range: [6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[6,7],ele2_num_range:[2],overlap_num : 2,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},


    "2901": {id : 2901,shown_time : 3,row_range: [4],column_range: [5],total_ele_num_range:[12],
        ele_type_num : 3,ele1_num_range:[4,5],ele2_num_range:[2],overlap_num : 1,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2902": {id : 2902,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[5,6],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2903": {id : 2903,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[5,6],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2904": {id : 2904,shown_time : 3,row_range: [6],column_range: [6],total_ele_num_range:[16],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[6,7],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2905": {id : 2905,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[6,7],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2906": {id : 2906,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[5,6],overlap_num : 4,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "2907": {id : 2907,shown_time : 3,row_range: [6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[5,6],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},


    "3001": {id : 3001,shown_time : 3,row_range: [6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[2],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "3002": {id : 3002,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[5,6],ele2_num_range:[6],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "3003": {id : 3003,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[17],
        ele_type_num : 3,ele1_num_range:[5,6],ele2_num_range:[5,6],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "3004": {id : 3004,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[5,6],ele2_num_range:[5,6],overlap_num : 4,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "3005": {id : 3005,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[5,6],ele2_num_range:[6,7],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "3006": {id : 3006,shown_time : 3,row_range: [5,6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[5,6],overlap_num : 4,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},
    "3007": {id : 3007,shown_time : 3,row_range: [6],column_range: [6],total_ele_num_range:[18],
        ele_type_num : 3,ele1_num_range:[6],ele2_num_range:[6],overlap_num : 3,
        target: {desc:pm_tip_config.tip,target_list:[1,2,3],target_num : 2}},            
}
