var dict_sm_level = {
	0 : {
    	id : 0,
    	energy_level : -1,
		learning_ability : "困难学习力",
		channal_count : 1,
		fish_count : {minCount : 6, maxCount : 8},
		fish_type : {fish_type_count : 3, color_type : 2, pic_type : 3},
		show_fish_number : 3,
		fish_goal_probability : {member : 2, denominator : 3},
		show_fish_height : 2,
		channal12_width : 650,
		fish_change_probability : {member : 1, denominator : 20},
		fish_direction_count : {channal1 : 1, channal2 : 0, channal3 : 0, channal4 : 0}
    },
    1 : {
    	id : 1,
    	energy_level : -1,
		learning_ability : "困难学习力",
		channal_count : 1,
		fish_count : {minCount : 40, maxCount : 50},
		fish_type : {fish_type_count : 3, color_type : 3, pic_type : 3},
		show_fish_number : 3,
		fish_goal_probability : {member : 1, denominator : 2},
		show_fish_height : 2,
		channal12_width : 650,
		fish_change_probability : {member : 1, denominator : 20},
		fish_direction_count : {channal1 : 1, channal2 : 0, channal3 : 0, channal4 : 0}
    },
    2 : {
    	id : 2,
    	energy_level : 0,
		learning_ability : "困难学习力",
		channal_count : 1,
		fish_count : {minCount : 45, maxCount : 60},
		fish_type : {fish_type_count : 3, color_type : 3, pic_type : 3},
		show_fish_number : 4,
		fish_goal_probability : {member : 1, denominator : 2},
		show_fish_height : 2,
		channal12_width : 630,
		fish_change_probability : {member : 1, denominator : 25},
		fish_direction_count : {channal1 : 1, channal2 : 0, channal3 : 0, channal4 : 0}
    },
    3 : {
    	id : 3,
    	energy_level : 0,
		learning_ability : "困难学习力",
		channal_count : 1,
		fish_count : {minCount : 50, maxCount : 70},
		fish_type : {fish_type_count : 3, color_type : 3, pic_type : 3},
		show_fish_number : 5,
		fish_goal_probability : {member : 9, denominator : 20},
		show_fish_height : 3,
		channal12_width : 600,
		fish_change_probability : {member : 1, denominator : 17},
		fish_direction_count : {channal1 : 2, channal2 : 0, channal3 : 0, channal4 : 0}
    },
    4 : {
    	id : 4,
    	energy_level : 1,
		learning_ability : "困难学习力",
		channal_count : 2,
		fish_count : {minCount : 70, maxCount : 90},
		fish_type : {fish_type_count : 4, color_type : 4, pic_type : 4},
		show_fish_number : 5,
		fish_goal_probability : {member : 7, denominator : 15},
		show_fish_height : 2,
		channal12_width : 600,
		fish_change_probability : {member : 1, denominator : 12},
		fish_direction_count : {channal1 : 1, channal2 : 1, channal3 : 0, channal4 : 0}
    },
    5 : {
    	id : 5,
    	energy_level : 1,
		learning_ability : "困难学习力",
		channal_count : 2,
		fish_count : {minCount : 80, maxCount : 100},
		fish_type : {fish_type_count : 3, color_type : 2, pic_type : 3},
		show_fish_number : 5,
		fish_goal_probability : {member : 8, denominator : 17},
		show_fish_height : 2,
		channal12_width : 600,
		fish_change_probability : {member : 1, denominator : 14},
		fish_direction_count : {channal1 : 1, channal2 : 1, channal3 : 0, channal4 : 0}
    },
    6 : {
    	id : 6,
    	energy_level : 2,
		learning_ability : "较低学习力",
		channal_count : 2,
		fish_count : {minCount : 90, maxCount : 110},
		fish_type : {fish_type_count : 3, color_type : 1, pic_type : 3},
		show_fish_number : 5,
		fish_goal_probability : {member : 9, denominator : 19},
		show_fish_height : 3,
		channal12_width : 570,
		fish_change_probability : {member : 1, denominator : 15},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 0, channal4 : 0}
    },
    7 : {
    	id : 7,
    	energy_level : 2,
		learning_ability : "较低学习力",
		channal_count : 3,
		fish_count : {minCount : 110, maxCount : 130},
		fish_type : {fish_type_count : 4, color_type : 4, pic_type : 3},
		show_fish_number : 5,
		fish_goal_probability : {member : 6, denominator : 13},
		show_fish_height : 3,
		channal12_width : 570,
		fish_change_probability : {member : 1, denominator : 12},
		fish_direction_count : {channal1 : 1, channal2 : 1, channal3 : 1, channal4 : 0}
    },
    8 : {
    	id : 8,
    	energy_level : 2,
		learning_ability : "较低学习力",
		channal_count : 3,
		fish_count : {minCount : 115, maxCount : 135},
		fish_type : {fish_type_count : 4, color_type : 3, pic_type : 3},
		show_fish_number : 5,
		fish_goal_probability : {member : 10, denominator : 21},
		show_fish_height : 3,
		channal12_width : 570,
		fish_change_probability : {member : 1, denominator : 13},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 0}
    },
    9 : {
    	id : 9,
    	energy_level : 3,
		learning_ability : "较低学习力",
		channal_count : 3,
		fish_count : {minCount : 120, maxCount : 140},
		fish_type : {fish_type_count : 4, color_type : 3, pic_type : 4},
		show_fish_number : 5,
		fish_goal_probability : {member : 1, denominator : 2},
		show_fish_height : 3,
		channal12_width : 570,
		fish_change_probability : {member : 1, denominator : 10},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 0}
    },
    10 : {
    	id : 10,
    	energy_level : 3,
		learning_ability : "较低学习力",
		channal_count : 4,
		fish_count : {minCount : 140, maxCount : 160},
		fish_type : {fish_type_count : 4, color_type : 2, pic_type : 4},
		show_fish_number : 5,
		fish_goal_probability : {member : 9, denominator : 19},
		show_fish_height : 3,
		channal12_width : 540,
		fish_change_probability : {member : 1, denominator : 9},
		fish_direction_count : {channal1 : 1, channal2 : 1, channal3 : 2, channal4 : 1}
    },
    11 : {
    	id : 11,
    	energy_level : 3,
		learning_ability : "较低学习力",
		channal_count : 4,
		fish_count : {minCount : 145, maxCount : 165},
		fish_type : {fish_type_count : 4, color_type : 1, pic_type : 4},
		show_fish_number : 5,
		fish_goal_probability : {member : 1, denominator : 2},
		show_fish_height : 3,
		channal12_width : 540,
		fish_change_probability : {member : 1, denominator : 9},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    12 : {
    	id : 12,
    	energy_level : 4,
		learning_ability : "较低学习力",
		channal_count : 4,
		fish_count : {minCount : 150, maxCount : 170},
		fish_type : {fish_type_count : 5, color_type : 2, pic_type : 3},
		show_fish_number : 5,
		fish_goal_probability : {member : 9, denominator : 20},
		show_fish_height : 3,
		channal12_width : 540,
		fish_change_probability : {member : 1, denominator : 9},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    13 : {
    	id : 13,
    	energy_level : 4,
		learning_ability : "较低学习力",
		channal_count : 4,
		fish_count : {minCount : 155, maxCount : 175},
		fish_type : {fish_type_count : 5, color_type : 3, pic_type : 3},
		show_fish_number : 5,
		fish_goal_probability : {member : 5, denominator : 11},
		show_fish_height : 3,
		channal12_width : 540,
		fish_change_probability : {member : 1, denominator : 9},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    14 : {
    	id : 14,
    	energy_level : 4,
		learning_ability : "较低学习力",
		channal_count : 4,
		fish_count : {minCount : 160, maxCount : 180},
		fish_type : {fish_type_count : 5, color_type : 4, pic_type : 3},
		show_fish_number : 5,
		fish_goal_probability : {member : 7, denominator : 15},
		show_fish_height : 3,
		channal12_width : 540,
		fish_change_probability : {member : 1, denominator : 10},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    15 : {
    	id : 15,
    	energy_level : 5,
		learning_ability : "一般学习力",
		channal_count : 4,
		fish_count : {minCount : 165, maxCount : 185},
		fish_type : {fish_type_count : 5, color_type : 3, pic_type : 4},
		show_fish_number : 5,
		fish_goal_probability : {member : 1, denominator : 2},
		show_fish_height : 3,
		channal12_width : 510,
		fish_change_probability : {member : 1, denominator : 8},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    16 : {
    	id : 16,
    	energy_level : 5,
		learning_ability : "一般学习力",
		channal_count : 4,
		fish_count : {minCount : 170, maxCount : 190},
		fish_type : {fish_type_count : 5, color_type : 3, pic_type : 4},
		show_fish_number : 5,
		fish_goal_probability : {member : 9, denominator : 20},
		show_fish_height : 3,
		channal12_width : 510,
		fish_change_probability : {member : 1, denominator : 8},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    17 : {
    	id : 17,
    	energy_level : 5,
		learning_ability : "一般学习力",
		channal_count : 4,
		fish_count : {minCount : 175, maxCount : 195},
		fish_type : {fish_type_count : 5, color_type : 4, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 6, denominator : 13},
		show_fish_height : 3,
		channal12_width : 510,
		fish_change_probability : {member : 1, denominator : 9},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    18 : {
    	id : 18,
    	energy_level : 5,
		learning_ability : "一般学习力",
		channal_count : 4,
		fish_count : {minCount : 180, maxCount : 200},
		fish_type : {fish_type_count : 5, color_type : 3, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 10, denominator : 21},
		show_fish_height : 3,
		channal12_width : 510,
		fish_change_probability : {member : 1, denominator : 9},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    19 : {
    	id : 19,
    	energy_level : 6,
		learning_ability : "一般学习力",
		channal_count : 4,
		fish_count : {minCount : 185, maxCount : 200},
		fish_type : {fish_type_count : 5, color_type : 2, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 5, denominator : 11},
		show_fish_height : 3,
		channal12_width : 510,
		fish_change_probability : {member : 1, denominator : 9},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    20 : {
    	id : 20,
    	energy_level : 6,
		learning_ability : "一般学习力",
		channal_count : 4,
		fish_count : {minCount : 190, maxCount : 205},
		fish_type : {fish_type_count : 5, color_type : 1, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 8, denominator : 17},
		show_fish_height : 3,
		channal12_width : 480,
		fish_change_probability : {member : 1, denominator : 9},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    21 : {
    	id : 21,
    	energy_level : 6,
		learning_ability : "一般学习力",
		channal_count : 4,
		fish_count : {minCount : 200, maxCount : 220},
		fish_type : {fish_type_count : 5, color_type : 1, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 6, denominator : 13},
		show_fish_height : 3,
		channal12_width : 480,
		fish_change_probability : {member : 1, denominator : 10},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    22 : {
    	id : 22,
    	energy_level : 6,
		learning_ability : "一般学习力",
		channal_count : 4,
		fish_count : {minCount : 210, maxCount : 230},
		fish_type : {fish_type_count : 5, color_type : 1, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 10, denominator : 21},
		show_fish_height : 3,
		channal12_width : 480,
		fish_change_probability : {member : 1, denominator : 9},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    23 : {
    	id : 23,
    	energy_level : 7,
		learning_ability : "较高学习力",
		channal_count : 4,
		fish_count : {minCount : 220, maxCount : 240},
		fish_type : {fish_type_count : 5, color_type : 1, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 7, denominator : 15},
		show_fish_height : 3,
		channal12_width : 480,
		fish_change_probability : {member : 1, denominator : 9},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    24 : {
    	id : 24,
    	energy_level : 7,
		learning_ability : "较高学习力",
		channal_count : 4,
		fish_count : {minCount : 210, maxCount : 230},
		fish_type : {fish_type_count : 5, color_type : 1, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 9, denominator : 20},
		show_fish_height : 3,
		channal12_width : 450,
		fish_change_probability : {member : 1, denominator : 9},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    25 : {
    	id : 25,
    	energy_level : 7,
		learning_ability : "较高学习力",
		channal_count : 4,
		fish_count : {minCount : 220, maxCount : 240},
		fish_type : {fish_type_count : 5, color_type : 1, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 9, denominator : 19},
		show_fish_height : 3,
		channal12_width : 450,
		fish_change_probability : {member : 1, denominator : 9},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    26 : {
    	id : 26,
    	energy_level : 8,
		learning_ability : "较高学习力",
		channal_count : 4,
		fish_count : {minCount : 230, maxCount : 250},
		fish_type : {fish_type_count : 5, color_type : 1, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 8, denominator : 17},
		show_fish_height : 3,
		channal12_width : 450,
		fish_change_probability : {member : 1, denominator : 10},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    27 : {
    	id : 27,
    	energy_level : 8,
		learning_ability : "较高学习力",
		channal_count : 4,
		fish_count : {minCount : 240, maxCount : 260},
		fish_type : {fish_type_count : 5, color_type : 1, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 10, denominator : 21},
		show_fish_height : 3,
		channal12_width : 450,
		fish_change_probability : {member : 1, denominator : 10},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    28 : {
    	id : 28,
    	energy_level : 8,
		learning_ability : "较高学习力",
		channal_count : 4,
		fish_count : {minCount : 240, maxCount : 265},
		fish_type : {fish_type_count : 5, color_type : 1, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 7, denominator : 15},
		show_fish_height : 3,
		channal12_width : 420,
		fish_change_probability : {member : 1, denominator : 10},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    29 : {
    	id : 29,
    	energy_level : 9,
		learning_ability : "高学习力",
		channal_count : 4,
		fish_count : {minCount : 250, maxCount : 280},
		fish_type : {fish_type_count : 5, color_type : 1, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 10, denominator : 21},
		show_fish_height : 3,
		channal12_width : 420,
		fish_change_probability : {member : 1, denominator : 12},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    },
    30 : {
    	id : 30,
    	energy_level : 10,
		learning_ability : "高学习力",
		channal_count : 4,
		fish_count : {minCount : 260, maxCount : 300},
		fish_type : {fish_type_count : 5, color_type : 1, pic_type : 5},
		show_fish_number : 5,
		fish_goal_probability : {member : 9, denominator : 20},
		show_fish_height : 3,
		channal12_width : 400,
		fish_change_probability : {member : 1, denominator : 11},
		fish_direction_count : {channal1 : 2, channal2 : 2, channal3 : 2, channal4 : 2}
    }
}